#include <bits/stdc++.h>
using namespace std;

const string YES = "YES";
const string NO = "NO";

void solve(long long A, long long B, long long C){
    int cnt5 = 0, cnt7 = 0;
    if(A==5)++cnt5;
    else if(A==7)++cnt7;
    if(B==5)++cnt5;
    else if(B==7)++cnt7;
    if(C==5)++cnt5;
    else if(C==7)++cnt7;

    if(cnt5==2 && cnt7==1) cout << YES << endl;
    else cout << NO << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long A;
    scanf("%lld",&A);
    long long B;
    scanf("%lld",&B);
    long long C;
    scanf("%lld",&C);
    solve(A, B, C);
    return 0;
}

